version: '3.4'

services:
  notesApp:
    image: ${DOCKER_REGISTRY-}notesApp
    build:
      context: .
      dockerfile: Dockerfile
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: notesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

